name: CI/CD

on:
  push:
    branches:
      - main
    # tags:
    ## `any` branch by default
    # branches: []

jobs:
  # 1.0 - Build
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=24.6.0"
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bot
          path: |
            ./bin
            ./dist
            ./scripts
            ./ecosystem.config.cjs.enc
            ./package.json

  # 2.0 - Deployment
  deploy:
    name: Deploy on server
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v5

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: bot
          path: bot

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Generate release name
        id: release_name
        run: echo "release_name=$(date "+%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Deploy with Rsync
        run: |
          rsync -avz -e ssh ./bot/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/discord-aoo/releases/${{ env.release_name }}/

      - name: Change current release version
        uses: appleboy/ssh-action@v1
        env:
          RELEASE_NAME: ${{ env.release_name }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: RELEASE_NAME
          script: |
            cd /var/www/discord-aoo
            ln -snf "releases/$RELEASE_NAME" current

  # 3.0 - Decrypt and start
  start:
    name: Decrypt and start process
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    steps:
      - uses: actions/checkout@v5

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Decrypt ecosystem file for PM2 and start/restart process
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/discord-aoo/current
            sops decrypt ecosystem.config.cjs.enc > ecosystem.config.cjs
            sudo chmod +x ./bin/*.sh
            ./bin/install.sh
            ./bin/pm2.sh
